### ISSUE TITLE
Could not find suitable distribution for Requirement.parse('django-bcp==0.1.8')

### ISSUE THREAD

**Issue by komuW** [adlibre/Adlibre-DMS#9]
When I ran:
pip install -e git+ssh://git@github.com/adlibre/Adlibre-DMS.git#egg=dms

I get the error: Could not find suitable distribution for Requirement.parse('django-bcp==0.1.8')
I looked at pypi and there doenst appear to be a version 0.18 but there is a version 0.2.2 that I did install instead.

**Comment by garmoncheg** [comment]
Updated master so it uses current BCP version
